steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Isso garante a compatibilidade com o seu package.json

      - name: Install Dependencies (Root)
        run: npm install

      # Opcional: Se você usa TS nas functions, o build precisa rodar aqui ou no predeploy
      - name: Install Functions Dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --force --project sitezing-4714c
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
