name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Ou a sua branch principal (master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies (Root)
        run: npm install

      - name: Install Functions Dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --force --project sitezing-4714c
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
