- name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --force --project sitezing-4714c
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
